platform :ios, '8.0’

target ‘BZY’ do


pod 'JPush'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'DFPlayer'
pod 'DZNEmptyDataSet'
pod 'JKCategories'
pod 'MBProgressHUD'
pod 'AFNetworking'
end

